In [11]:
""" ann 09 -->                 Write a python program to design a Hopfield Network which stores 4 vectors.                                                                                                   
the Hopfield network is trained by calculating the weight matrix using the dot product of the 
patterns with their transpose. The diagonal elements of the weight matrix are set to zero.To recall a pattern, a recall pattern is 
provided, and the retrieved pattern is obtained by taking the sign of the dot product of the weight matrix with the recall pattern.
The retrieved pattern is then printed.
Please note that in this simplified version, the sign activation function is used instead of the signum function to calculate the 
sign of the dot product. This works because the patterns are binary values of 1 and -1."""

import numpy as np
# Define the patterns to be stored
patterns = np.array([
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [1, 1, -1, -1],
    [-1, -1, 1, 1]
])
# Train the Hopfield network
weights = np.dot(patterns.T, patterns)
print(weights)
np.fill_diagonal(weights, 0)
print(weights)
# Recall a pattern
recall_pattern = np.array([-1, -1, 1, 1])
retrieved_pattern = np.sign(np.dot(weights, recall_pattern))
print("Retrieved Pattern:")
print(retrieved_pattern)
print(np.dot(weights, recall_pattern))


[[ 4  0  0 -4]
 [ 0  4 -4  0]
 [ 0 -4  4  0]
 [-4  0  0  4]]
[[ 0  0  0 -4]
 [ 0  0 -4  0]
 [ 0 -4  0  0]
 [-4  0  0  0]]
Retrieved Pattern:
[-1 -1  1  1]
[-4 -4  4  4]
